name: CI
on: [push, pull_request]
jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.13
      id: go
    - name: Install dependencies
      run: |
        go get github.com/mattn/goveralls
        go get github.com/modocache/gover
        sudo apt-get install -y conntrack
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Unit tests
      run: |
        make test/unit
    - name: Run e2e tests
      run: |
        make setup/github
        sudo chown -R $USER $HOME/.kube $HOME/.minikube
        make cluster/prepare 
        make test/e2e
    - name: Run e2e tests for local image
      run: |
        make test/e2e-local-image
    - name: After failure
      if: ${{ failure() }}
      run: |
        echo "---- Keycloak Server logs ----"
        kubectl logs keycloak-0
        echo "---- Testing Ingress ----"
        curl -kv https://keycloak.local/auth
        echo "---- Ingress Controller logs ----"
        kubectl logs -l app.kubernetes.io/name=nginx-ingress-controller -n kube-system